### ISSUE TITLE
Provide commentary on any requirements layered on the OAuth threat model

### ISSUE THREAD

**Issue by findthomas** [xmlgrrl/UMA-Specifications#10]
Provide commentary on any requirements layered on the forthcoming OAuth security considerations section; discuss UMA-layer implications for more meaningful authentication of requesters/requesting parties; discuss implications of user-mediated AM/host trust model; discuss short-lived token technique for lightweight requester correlation... (Someone want to take this AI?) 

[Previously #18]

**Comment by xmlgrrl** [comment]
Changed the issue name to reflect the fact that the threat model has been published.

**Comment by xmlgrrl** [comment]
Re Domenico's comments from Dec 10, 2012, I believe we have handled the "implicit"/"person to person" security considerations and also the "status"/"redirect" security considerations in Core rev 11f, Section 8.1, Redirection and Impersonation Threats (https://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.8.1).

Re my comments from Aug 5, 2012, I believe we have handled the "host as client", "requester as client", "AM as protection API server", and "AM as authorization API server" security considerations in Core rev 11f, Section 8.2, Client Authentication (https://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.8.2), as well as throughout the text. We have handled the fact that "authorizing user/requesting party" is "person to person" as already noted above.

We have accounted for privacy considerations that map to security considerations as they have come up in our analysis work.

We could probably do with more discussion about the relationship between RPTs and different kinds of UMA clients (public, confidential, etc.) to see if there are particular threat scenarios there, at least in light of the one kind of RPT profile we have so far.

**Comment by xmlgrrl** [comment]
One more security consideration worth discussing: Are there any security considerations related to the icon_uri supplied in Section 2.1 (scope description) and Section 2.2 (resource set description) during resource set registration? What if it's a third-party URI and it contains something malicious? The AS is vulnerable to the RS picking "good" icon sources. If the domain matching the RS's own domain, the risk is perhaps lower, but perhaps not even. There are actually two levels of risk: Loading malicious code, and displaying a misleading icon to the RO (something like the "display name" problem). Should we say anything about this? Any current practices to be aware of? Any mitigations?

**Comment by xmlgrrl** [comment]
Most of these have been dealt with in Core rev 11, the V1.0 candidate. Created new issue #125 as a bucket for new security considerations.
