### ISSUE TITLE
Editorial issues on Core rev 11f

### ISSUE THREAD

**Issue by xmlgrrl** [xmlgrrl/UMA-Specifications#120]
Roland reported the following issues. I'll follow each with a recommended disposition.

1.
In 3.4.1.2.2:
"The client MUST ignore unrecognized response parameters. The authorization code string size is left undefined by this specification. The client should avoid making assumptions about code value sizes. The authorization server SHOULD document the size of any value it issues.”
Up until that point there is no mentioning of an authorization code in 3.4.1.2.2, it’s definitely not mentioned as one of the parameters the authorization server is returning.

Eve's recommendation: This was a copy/paste error from OAuth or OIDC. Remove the sentences after the first one.

2.
Section 1.3.1 paragraph after the list of endpoints:
’.. an entity with this scope is by definition a resource server’
should be 
’.. an entity that can acquire an access token with this scope is by definition a resource server’
and
Section 1.3.2 paragraph after the list of endpoints:
’.. an entity with this scope is by definition a client’
should be 
’.. an entity that can acquire an access token with this scope is by definition a client’

Eve's recommendation: Accept.

3.
1.3.1 and 1.3.2
’A single entity can serve in both resource server and client roles if it has the appropriate OAuth scopes.’
wouldn’t this be better ?
'A single entity can serve in both resource server and client roles if it has access tokens with the appropriate OAuth scopes’

Eve's recommendation: Accept (in both locations).

4.
1.3.1 and 1.3.2
’The authorization server thus has an OAuth token endpoint and authorization endpoint, and has the option to issue an OAuth refresh token along with any access tokens issued for these APIs.'
what ?
The authorization server thus has an OAuth token endpoint and authorization endpoint. (full stop)
Whether it can issue a refresh token depends on which grant type is used and is defined
by OAuth, so why bring it up here ?

Eve's recommendation: Accept (in both locations).

5.
1.3.1, last sentence:
”The issuance of a PAT represents the approval of the resource owner for this resource server to use this authorization server for protecting its resources belonging to this resource owner."
I don’t think there is supposed to be a one-one mapping between all a resources owners resources 
at a resource server and an authorization server.
I think the idea is that a resource owner may use several authorization servers for protecting
resources at a resource server.
So:
”The issuance of a PAT represents the approval of the resource owner for this resource server to use this authorization server for protecting some or all of the resources belonging to this resource owner.”

Eve's recommendation: Accept.

6.
1.4:
'dynamic_client_endpoint
OPTIONAL. The endpoint to use for performing dynamic client registration in the case of the use of [DynClientReg], or alternatively the reserved string "openid" in the case of the use of [OIDCDynClientReg]. In the latter case, it is presumed that the resource server or client will discover the dynamic client registration endpoint from the authorization server’s published configuration data.’
Wouldn’t hurt (?) to be more explicit:
’In the latter case, it is presumed that the resource server or client will discover the dynamic client registration endpoint from the authorization server’s published OpenID Provider Configuration Information.’
and possibly a reference to 
http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

Eve's recommendation: Change to "...published OpenID Provider Configuration Information." Leave out the reference. It's sufficient to formally name the kind of config data; no need to do the implementer's work for them in looking up the reference to a "foreign" spec.

7.
Should probably be:
{
 "error": "need_info",
 "error_details": {
   "authentication_context": {
     "required_acr": ["https://example.com/acrs/LOA3.14159"]
   },
   "requesting_party_claims": {
     "required_claims": [
       {
         "name": "email23423453ou453",
         "friendly_name": "email",
         "claim_type": "urn:oid:0.9.2342.19200300.100.1.3",
         "claim_token_format": ["http://openid.net/specs/openid-connect-core-1_0.html#HybridIDToken"],
         "issuer": ["https://example.com/idp"]
       }
     ],
     "redirect_user": "yes",
     "ticket": "016f84e8-f9b9-11e0-bd6f-0021cc6004de"
   }
 }
}

Eve's recommendation: I'm going to assume Roland's JSON is correct and mine is broken, so: Accept!

8.
Section 3:
At the end of the high-level summary the same paragraph appears twice one indented one 
level more then the other.

Eve's recommendation: Reject. It's not the same paragraph; they differ in a crucial respect ("If the access attempt is unaccompanied by an RPT..." vs. "If the RPT is invalid, or if the RPT is valid but has insufficient authorization data...").

9.
3.4.1:
”The authorization server uses the ticket to look up the details of the previously registered requested permission, maps the requested permission to operative resource owner policies based on the resource set identifier and scopes associated with it, potentially provides interim responses and undergoes additional information collection, and ultimately responds to the request with finality.”
’.. potentially provides interim responses ..’
Whatever are intermin responses ?
Is that the ’need_info’ response ? 
Or does that fall under additional information collection ?
Interim response to me is like the spinning ball, wait and eventually something will happen.
But no more input is needed from the user !
Which is not what ’need_info’ is about.
I think there where somewhere mentioned that a request may not be covered by rules set
up by the resource owner so the requestor was told by the AS: ”I’ll have to contact the resource owner,
I’ll get back to you. Don’t call me I’ll call you !!” kind of thing.

Eve's recommendation: The intent behind "interim" was to elide a lot of detail in this high-level summary, in order to let readers just get into the details of the spec when they're ready. We could say something like this instead: "...potentially requests additional information, and ultimately responds positively or negatively to the request for authorization data." This maps fairly directly to "need_info", to "not_authorized", and to "success", and it accounts for error responses as well.

**Comment by rohe** [comment]
> 8.
> Section 3:
> At the end of the high-level summary the same paragraph appears twice one indented one 
> level more then the other.
> 
> Eve's recommendation: Reject. It's not the same paragraph; they differ in a crucial respect ("If the access attempt is unaccompanied by an RPT..." vs. ”If the RPT is invalid, or if the RPT is valid but has insufficient authorization data...").

The two paragraphs I was referring to was:

	• If the client does not already have an AAT at the appropriate authorization server to be able to use its authorization API, it first obtains one.
		• If the client does not already have an AAT at the appropriate authorization server to be able to use its authorization API, it first obtains one.

We’re probably not talking about the same thing.

— Roland

”Being able to think like a child is an important attribute of being an adult” - Eddie Izzard

**Comment by xmlgrrl** [comment]
Re item no. 8: Aha, I see now. Indeed, that is an editing oversight, and should be corrected.

**Comment by xmlgrrl** [comment]
Oops, I see that I also forgot to mention "profiles" in Section 8.4 of Core, as I promised. This still needs to be done.

**Comment by xmlgrrl** [comment]
All edited into the amended Core rev 11 approved in UMA telecon 2015-01-05.
