### ISSUE TITLE
redirect_user hint: Use JSON Boolean data type

### ISSUE THREAD

**Issue by xmlgrrl** [xmlgrrl/UMA-Specifications#121]
From Roland H, on Core rev 11f:
3.4.1.2:
Why is ’redirect_user’ ”yes”/"no" and not true/false which would be more JSON :-)

**Comment by GilKirkpatrick** [comment]
I agree with Roland, we should stick with standard encodings.

**Comment by xmlgrrl** [comment]
Implemented in Core rev 11 approved as amended after UMA telecon 2015-01-05.
