### ISSUE TITLE
Security considerations to discuss

### ISSUE THREAD

**Issue by xmlgrrl** [xmlgrrl/UMA-Specifications#125]
Preserving these in order to be able to close most of issue #10:

We could probably do with more discussion about the relationship between RPTs and different kinds of UMA clients (public, confidential, etc.) to see if there are particular threat scenarios there, at least in light of the one kind of RPT profile we have so far.

One more security consideration worth discussing: Are there any security considerations related to the icon_uri supplied in Section 2.1 (scope description) and Section 2.2 (resource set description) during resource set registration? What if it's a third-party URI and it contains something malicious? The AS is vulnerable to the RS picking "good" icon sources. If the domain matching the RS's own domain, the risk is perhaps lower, but perhaps not even. There are actually two levels of risk: Loading malicious code, and displaying a misleading icon to the RO (something like the "display name" problem). Should we say anything about this? Any current practices to be aware of? Any mitigations?

**Comment by IDmachines** [comment]
can you sign the icon as mitigation?

**Comment by xmlgrrl** [comment]
As discussed in UMA telecon 2015-02-19: Icon URI (for resource sets and scopes) threats: The RS itself has a trust relationship with the AS in question, and it registers resources in the context of a particular RO. If an RS is malicious, it would have to get a user to authorize it to (a) dynamically register and (b) outsource protection to the AS. Perhaps a mitigation is that an AS may not want to display scope or resource set icons of a dynamically-registered-client-as-RS until such time as it establishes sufficient trust. A choice on the RS side that increases the likelihood of the AS displaying its icons even if the RS is less trusted, could be to choose icons that are well-known and standardized by third parties. Do we have to worry about the threat of retrieving the scope description from the scope URI, similarly to an icon URI? No, because the endpoint should just contain a hunk of JSON, and we already say something about that in an abundance of caution; JSON should not be unthinkingly executed. Consensus to add new discussion of threats/mitigations.

**Comment by xmlgrrl** [comment]
This looks like it's really an RSR security consideration. Added a new warning in Core rev 12a for implementers to read the security considerations in RSR.

**Comment by xmlgrrl** [comment]
New security consideration added to RSR rev 05a.
