### ISSUE TITLE
Minor issues in Core

### ISSUE THREAD

**Issue by tsitkov** [xmlgrrl/UMA-Specifications#126]
1.  In Core section  3.4.1 the second paragraph reads “attempt, It MAY” - uppercased “It”

2. In Core section 1.3.3 'This specification defines one RPT profile, call "bearer”'. Should be "called"

3. In Core section 3.4.1 in the example  "POST /authz_request HTTP/1.1" should be "POST /rpt_uri HTTP/1.1" to be consistent with the example given in section 1.4

**Comment by xmlgrrl** [comment]
Execute on these.

**Comment by tsitkov** [comment]
Similar to #3: 
in section 3.4.1.2.1 in the example "rpt_authorization" should be replace by rpt_uri

**Comment by tsitkov** [comment]
5. Typo in 3.4.1.2.2 "when adding addition parameters"
6. Uppercased "STRONGLY RECOMMENDED". "STRONGLY" is not rfc2119 key word
7. in section 3.4.1.2.2 in the example "rqp_claim" should be replace by rqp_claims_uri
