### ISSUE TITLE
Boolean values

### ISSUE THREAD

**Issue by tsitkov** [xmlgrrl/UMA-Specifications#127]
“Boolean values”  - uppercased or not and allowed values. 
 Eve commented on this one:
"... the JSON spec itself doesn't say "Boolean", and also allows "null":
https://tools.ietf.org/html/rfc7159#section-3"
Should we revise this to include "null"?  Should we just list the literal values and describe them the way the JSON spec itself does?

**Comment by xmlgrrl** [comment]
We have two usages of something Boolean. The first comes from the "active" claim in the introspection spec, in Section 2.2:

http://tools.ietf.org/html/draft-ietf-oauth-introspection-04#section-2.2

...where it just says "Boolean", and isn't clear whether null is an option or not. Non-normative examples show only true and false. Eve was wrong about the JSON spec not saying "Boolean" (though it spells it lowercase), though it does literally list true, false, and null. In the "active" case, we should probably alert Justin Richer to the potential ambiguity. Presumably the fact that it's a required property means that it should never be null, but it's good to be explicit.

The second is for the "redirect_user" hint. (The non-normative hint example has a bug in it; it needs to say true, not "yes".) Given the logic above, it suggests that null is not needed as a value, so we could say that the value is "a Boolean value, either true or false".

Agreed to do that.
