### ISSUE TITLE
RSR: Why does List resource set have an If-Match?

### ISSUE THREAD

**Issue by xmlgrrl** [xmlgrrl/UMA-Specifications#129]
The example of "listing" doesn't have an If-Match, but Section 2.3 mentions If-Match. Is this mention an oversight?

**Comment by mmachulak** [comment]
Eve, "If-Match" should not be used in the List resource set operation.

Cheers,
Maciej

On 26 January 2015 at 12:49, Eve Maler <notifications@github.com> wrote:

> The example of "listing" doesn't have an If-Match, but Section 2.3
> mentions If-Match. Is this mention an oversight?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xmlgrrl/UMA-Specifications/issues/129>.
>



-- 
Maciej Machulak
email: maciej.machulak@gmail.com
mobile: +44 7999 606 767 (UK)
mobile: +48 602 45 31 66 (PL)

**Comment by xmlgrrl** [comment]
Agreed in UMA telecon 2015-02-19: This should be removed. Done in RSR rev 05a.
