### ISSUE TITLE
OAuth 2.0 Resource Set Registration word missing in 2.3

### ISSUE THREAD

**Issue by IDmachines** [xmlgrrl/UMA-Specifications#131]
Grammar goof  in RSR 2.3 RSR API  "The method of authentication that the resource server uses SHOULD sufficient context to distinguish between identical resource set identifiers assigned by different resource servers."

Perhaps add the word "provide" or equivalent after SHOULD

**Comment by xmlgrrl** [comment]
This sentence is obsoleted by our subsequent decision to change the PUT for creation to POST; RS's no longer choose their own rsid's. Reworded in RSR rev 05a.
