### ISSUE TITLE
Adding examples to Core

### ISSUE THREAD

**Issue by tsitkov** [xmlgrrl/UMA-Specifications#138]
1. Consider adding "request" example to https://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.3.3.2 
2. Consider adding example to https://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.3.4.1.2 in general, and to clarify text for "name" ("the actual name is complex or opaque, such as an OID or a UUID.")
3. https://docs.kantarainitiative.org/uma/draft-uma-core.html#rfc.section.3.4.1.2.2: typo "If the the URI "

**Comment by xmlgrrl** [comment]
#1 An example appears in Sec 3.1.2, so we could add a cross-reference to that section in order not to repeat content.
#2 An example appears in Sec 3.4.1, so we could add a cross-reference to that section in order not to repeat content. I'm not sure what the question is around the interpretation is of "name" vs. "friendly name". Do you think we have to expand "OID" and "UUID"? The example hopefully makes it clear, and these abbreviations are pretty well known. We already changed the example based on requests.
#3 Thanks for the catch!

**Comment by tsitkov** [comment]
adding references to the examples for #1 and #2 would work!

**Comment by xmlgrrl** [comment]
Done in Core rev 12a!
