### ISSUE TITLE
No definition for authorization server in Core

### ISSUE THREAD

**Issue by xmlgrrl** [xmlgrrl/UMA-Specifications#142]
The Core spec (Sec 1.2) has no definition for "authorization server". Was this an oversight?

**Comment by IDmachines** [comment]
Is this in the OAuth or AM as AS UMA sense of AS?  Or is this the issue?

**Comment by xmlgrrl** [comment]
Yes, that's the issue; it differs from OAuth. Definitions aren't testable assertions, though, so it's not normative text... Resolved in the final Recommendation (Core rev 13).
